# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80)),
                ('categoria_pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subcategoria', to='core.Categoria')),
            ],
            options={
                'db_table': 'Categoria',
                'ordering': ['categoria'],
                'verbose_name_plural': 'categorias',
                'verbose_name': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('endereco', models.CharField(max_length=100, null=True, verbose_name='endereço')),
                ('complemento', models.CharField(max_length=20, null=True)),
                ('bairro', models.CharField(max_length=60, null=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'ordering': ['nome'],
                'verbose_name_plural': 'clientes',
                'verbose_name': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço')),
            ],
            options={
                'verbose_name': 'itens_pedido',
                'db_table': 'Intens_Pedidos',
                'verbose_name_plural': 'itens_pedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=60)),
            ],
            options={
                'db_table': 'Municipio',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='data pedido')),
                ('data_envio', models.DateTimeField(blank=True, verbose_name='data envio')),
                ('data_entrega', models.DateTimeField(blank=True, verbose_name='data entrega')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'db_table': 'Pedido',
                'ordering': ['data_pedido'],
                'verbose_name_plural': 'pedidos',
                'verbose_name': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.FileField(upload_to='')),
                ('preço', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'db_table': 'Produto',
                'ordering': ['nome'],
                'verbose_name_plural': 'produtos',
                'verbose_name': 'produto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.SmallIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('sigla', models.CharField(db_column='Sigla', max_length=2)),
            ],
            options={
                'db_table': 'UF',
                'ordering': ['sigla'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Produto')),
                ('quantidade', models.IntegerField()),
                ('minimo', models.IntegerField(default=0, verbose_name='estoque mínimo')),
            ],
            options={
                'verbose_name': 'estoque',
                'db_table': 'Estoque',
                'managed': True,
                'ordering': ['quantidade'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(through='core.ItensPedido', to='core.Produto'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='iduf',
            field=models.ForeignKey(db_column='IdUF', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Uf'),
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Uf', verbose_name='estado'),
        ),
    ]
